name: vernon_cms_ui
description: Vernon CMS UI — Web PWA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^14.8.1

  # Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Functional Programming (Either)
  dartz: ^0.10.1

  # Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1

  # Utils
  intl: ^0.20.2
  logger: ^2.5.0
  url_strategy: ^0.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts: []
